### ISSUE TITLE
Homebrew postinstall fails on Big Sur

### ISSUE THREAD

**Issue by neckro** [mediamicroservices/mm#279]
I'm getting this trying to install on Big Sur.  Not sure what exactly is failing here.

```
$ brew postinstall --debug mediamicroservices/mm/mm
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/mediamicroservices/homebrew-mm/mm.rb
==> Postinstalling mm
==> updatingplist
Last 15 lines from /Users/neckro/Library/Logs/Homebrew/mm/post_install.01.updatingplist:
2021-06-02 17:28:34 -0500

updatingplist

Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall mediamicroservices/mm/mm
==> An exception occurred within a child process:
  BuildError: Failed executing: updatingplist

/usr/local/Homebrew/Library/Homebrew/formula.rb:2173:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2109:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2109:in `system'
/usr/local/Homebrew/Library/Taps/mediamicroservices/homebrew-mm/mm.rb:89:in `post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1101:in `block (2 levels) in run_post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:924:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1100:in `block in run_post_install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:558:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1089:in `run_post_install'
/usr/local/Homebrew/Library/Homebrew/postinstall.rb:22:in `<main>'
```

Full contents of `/Users/neckro/Library/Logs/Homebrew/mm/post_install.01.updatingplist`:

```
2021-06-02 17:29:10 -0500

updatingplist


HOMEBREW_VERSION: 3.1.9-108-gaa937b9
ORIGIN: https://github.com/Homebrew/brew
HEAD: aa937b902410ced9b4baa57170c289f6a26699ce
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 268da91d776128e1467b6ff16a60b51cf9de2e25
Core tap last commit: 34 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.Vujyat7ac1/org.macosforge.xquartz:0
HOMEBREW_EDITOR: /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl -w
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_BOOTSNAP: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 12.0.5 build 1205
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.3.1-x86_64
CLT: 12.5.0.22.9
Xcode: 12.5
XQuartz: 2.7.11 => /opt/X11

HOMEBREW_GIT: git
PATH: /Users/neckro/bin:/usr/local/bin:/usr/local/sbin:/usr/local/share/npm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
```

**Comment by neckro** [comment]
Running `updatingplist` manually doesn't show any output but it does return error code 1 which may be why it's blowing up.

**Comment by neckro** [comment]
Changing `exit` to `exit 0` in the `updatingplist` script seems to fix this.

**Comment by retokromer** [comment]
>Changing `exit` to `exit 0` in the `updatingplist` script seems to fix this.

Indeed, this is a known bug.
